package com.foodreels.backend.integration;

import java.math.BigDecimal;
import java.util.UUID;
import javax.sql.DataSource;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import static org.assertj.core.api.Assertions.assertThat;

class FlywayMigrationTests {
    @Test
    void startup_shouldRunFlywayAndCreateMissingOrderTablesBeforeHardening() {
        DataSource dataSource = existingCoreDatabase();
        new ApplicationContextRunner()
                .withConfiguration(AutoConfigurations.of(FlywayAutoConfiguration.class))
                .withBean(DataSource.class, () -> dataSource)
                .withPropertyValues("spring.flyway.baseline-on-migrate=true",
                        "spring.flyway.baseline-version=1")
                .run(context -> {
                    assertThat(context).hasNotFailed().hasSingleBean(Flyway.class);
                    assertThat(context.getBean(Flyway.class).info().current().getVersion().toString())
                            .isEqualTo("2");
                    JdbcTemplate jdbc = new JdbcTemplate(dataSource);
                    insertOrder(jdbc);
                    insertItem(jdbc);
                    assertThat(jdbc.queryForObject("SELECT subtotal FROM order_items WHERE id = 31", BigDecimal.class))
                            .isEqualByComparingTo("251.00");
                    assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM information_schema.indexes "
                            + "WHERE index_name = 'idx_order_items_order'", Integer.class)).isEqualTo(1);
                });
    }

    @Test
    void migration_shouldPreserveExistingOrdersWhenOrderItemsAreMissing() {
        DataSource dataSource = existingCoreDatabase();
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE orders (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users(id),
                    restaurant_id BIGINT NOT NULL REFERENCES restaurants(id),
                    total_amount NUMERIC(12,2) NOT NULL, status VARCHAR(30) NOT NULL,
                    delivery_address VARCHAR(500) NOT NULL,
                    created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL)
                """);
        insertOrder(jdbc);
        Flyway flyway = flyway(dataSource);
        assertThat(flyway.migrate().migrationsExecuted).isEqualTo(2);
        assertThat(jdbc.queryForObject("SELECT delivery_address FROM orders WHERE id = 21", String.class))
                .isEqualTo("Existing address");
        insertItem(jdbc);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM order_items", Integer.class)).isEqualTo(1);
    }

    @Test
    void repeatedStartup_shouldPreserveOrderAndItemData() {
        DataSource dataSource = existingCoreDatabase();
        Flyway flyway = flyway(dataSource);
        flyway.migrate();
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        insertOrder(jdbc);
        insertItem(jdbc);
        assertThat(flyway.migrate().migrationsExecuted).isZero();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM orders", Integer.class)).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM order_items", Integer.class)).isEqualTo(1);
    }

    private DataSource existingCoreDatabase() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:migration_" + UUID.randomUUID()
                        + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1", "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        // These tables predate the order module. Fixture IDs are local to this isolated database.
        jdbc.execute("CREATE TABLE users (id BIGINT PRIMARY KEY)");
        jdbc.execute("CREATE TABLE restaurants (id BIGINT PRIMARY KEY)");
        jdbc.execute("CREATE TABLE foods (id BIGINT PRIMARY KEY)");
        jdbc.update("INSERT INTO users VALUES (11)");
        jdbc.update("INSERT INTO restaurants VALUES (12)");
        jdbc.update("INSERT INTO foods VALUES (13)");
        return dataSource;
    }

    private Flyway flyway(DataSource dataSource) {
        return Flyway.configure().dataSource(dataSource).baselineOnMigrate(true).baselineVersion("1")
                .locations("classpath:db/migration").load();
    }

    private void insertOrder(JdbcTemplate jdbc) {
        jdbc.update("""
                INSERT INTO orders (id, user_id, restaurant_id, total_amount, status,
                                    delivery_address, created_at, updated_at)
                VALUES (21, 11, 12, 251.00, 'CREATED', 'Existing address', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """);
    }

    private void insertItem(JdbcTemplate jdbc) {
        jdbc.update("""
                INSERT INTO order_items (id, order_id, food_id, quantity, unit_price, subtotal)
                VALUES (31, 21, 13, 2, 125.50, 251.00)
                """);
    }
}
